# Generated by Django 5.0b1 on 2023-11-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
