# Generated by Django 5.0b1 on 2023-11-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_alter_problem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_archive',
            field=models.FileField(default=None, upload_to='static/problems/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_xml',
            field=models.FileField(default=None, upload_to='static/problems/'),
            preserve_default=False,
        ),
    ]
