# Generated by Django 5.0b1 on 2023-11-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_problem_problem_archive_problem_problem_xml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_archive',
            field=models.FileField(upload_to='problems/'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_xml',
            field=models.FileField(upload_to='problems/'),
        ),
    ]
