# Generated by Django 5.0b1 on 2023-11-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_alter_problem_problem_archive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='description',
        ),
        migrations.AddField(
            model_name='problem',
            name='statement',
            field=models.JSONField(default={}),
        ),
    ]
