# Generated by Django 5.0b1 on 2023-11-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_remove_problem_description_problem_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='statement',
            field=models.JSONField(default=dict),
        ),
    ]
