# Generated by Django 5.0b1 on 2023-11-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_alter_submission_owner_alter_submission_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='source',
            field=models.FileField(default=None, upload_to='static/submissions/'),
            preserve_default=False,
        ),
    ]
