# Generated by Django 5.0b1 on 2023-11-13 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compilers', '0001_initial'),
        ('submissions', '0003_submission_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='compiler',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='compilers.compiler'),
            preserve_default=False,
        ),
    ]
