# Generated by Django 5.0b1 on 2023-11-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_submission_compiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='timestamp',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
