# Generated by Django 5.0b1 on 2023-11-13 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_alter_submission_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='timestamp',
        ),
    ]
