# Generated by Django 5.0b1 on 2023-11-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_remove_submission_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
