# Generated by Django 5.0b1 on 2023-11-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0008_submission_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='verdict',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='source',
            field=models.FileField(upload_to='submissions/'),
        ),
    ]
