# Generated by Django 5.0b1 on 2023-11-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compiler',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('compile_command', models.CharField(max_length=1024)),
                ('run_command', models.CharField(max_length=1024)),
            ],
        ),
    ]
