# Generated by Django 5.0b1 on 2023-11-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compilers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compiler',
            name='file_extension',
            field=models.CharField(default='.cpp', max_length=16),
            preserve_default=False,
        ),
    ]
